# Generated by Django 5.2.16 on 2026-07-10 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_postgres_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        # 1. Journal balance trigger function and deferred constraint trigger
        cursor.execute("""
            CREATE OR REPLACE FUNCTION check_journal_balance()
            RETURNS TRIGGER AS $$
            DECLARE
                v_journal_id bigint;
                v_debit_sum numeric;
                v_credit_sum numeric;
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    v_journal_id := OLD.journal_id;
                ELSE
                    v_journal_id := NEW.journal_id;
                END IF;

                -- Calculate sums of debits and credits
                SELECT COALESCE(SUM(debit), 0), COALESCE(SUM(credit), 0)
                INTO v_debit_sum, v_credit_sum
                FROM accounting_journalline
                WHERE journal_id = v_journal_id;

                -- Verify balance
                IF v_debit_sum <> v_credit_sum THEN
                    RAISE EXCEPTION 'Journal % is unbalanced. Total debits (%) must equal total credits (%).',
                        v_journal_id, v_debit_sum, v_credit_sum;
                END IF;

                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;
        """)
        cursor.execute("""
            CREATE CONSTRAINT TRIGGER trigger_check_journal_balance
            AFTER INSERT OR UPDATE OR DELETE ON accounting_journalline
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW
            EXECUTE FUNCTION check_journal_balance();
        """)

        # 2. Closed period check trigger
        cursor.execute("""
            CREATE OR REPLACE FUNCTION check_period_not_closed()
            RETURNS TRIGGER AS $$
            DECLARE
                v_date date;
                v_closed_period_exists boolean;
                v_tenant_id uuid;
            BEGIN
                IF TG_TABLE_NAME = 'accounting_journal' THEN
                    IF TG_OP = 'DELETE' THEN
                        v_date := OLD.date;
                        v_tenant_id := OLD.tenant_id;
                    ELSE
                        v_date := NEW.date;
                        v_tenant_id := NEW.tenant_id;
                    END IF;
                ELSIF TG_TABLE_NAME = 'accounting_journalline' THEN
                    IF TG_OP = 'DELETE' THEN
                        SELECT date, tenant_id INTO v_date, v_tenant_id FROM accounting_journal WHERE id = OLD.journal_id;
                    ELSE
                        SELECT date, tenant_id INTO v_date, v_tenant_id FROM accounting_journal WHERE id = NEW.journal_id;
                    END IF;
                END IF;

                IF v_date IS NOT NULL AND v_tenant_id IS NOT NULL THEN
                    SELECT EXISTS (
                        SELECT 1 FROM accounting_accountingperiod
                        WHERE tenant_id = v_tenant_id 
                          AND start_date <= v_date 
                          AND end_date >= v_date 
                          AND is_closed = TRUE
                    ) INTO v_closed_period_exists;

                    IF v_closed_period_exists THEN
                        RAISE EXCEPTION 'Operation blocked. The date % falls within a closed accounting period.', v_date;
                    END IF;
                END IF;

                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                ELSE
                    RETURN NEW;
                END IF;
            END;
            $$ LANGUAGE plpgsql;
        """)
        cursor.execute("""
            CREATE TRIGGER trigger_check_journal_period
            BEFORE INSERT OR UPDATE OR DELETE ON accounting_journal
            FOR EACH ROW
            EXECUTE FUNCTION check_period_not_closed();
        """)
        cursor.execute("""
            CREATE TRIGGER trigger_check_journalline_period
            BEFORE INSERT OR UPDATE OR DELETE ON accounting_journalline
            FOR EACH ROW
            EXECUTE FUNCTION check_period_not_closed();
        """)

        # 3. Immutability of Audit Log
        cursor.execute("""
            CREATE OR REPLACE FUNCTION block_audit_log_modification()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'Audit log entries are immutable and cannot be updated or deleted.';
            END;
            $$ LANGUAGE plpgsql;
        """)
        cursor.execute("""
            CREATE TRIGGER trigger_block_audit_log_modification
            BEFORE UPDATE OR DELETE ON accounting_auditevent
            FOR EACH ROW
            EXECUTE FUNCTION block_audit_log_modification();
        """)

        # 4. PostgreSQL RLS isolation policies
        # Create non-superuser tenant role for RLS testing and security enforcement
        cursor.execute("""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'ledger_tenant_role') THEN
                    CREATE ROLE ledger_tenant_role;
                END IF;
            END
            $$;
        """)
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_journal TO ledger_tenant_role;")
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_journalline TO ledger_tenant_role;")
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_accountingperiod TO ledger_tenant_role;")
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_auditevent TO ledger_tenant_role;")
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_nominalaccount TO ledger_tenant_role;")
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_tenant TO ledger_tenant_role;")
        cursor.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ledger_tenant_role;")

        # Enable and Force RLS (to apply to the table owner connection as well)
        cursor.execute("ALTER TABLE accounting_journal ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_journal FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_journalline ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_journalline FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_accountingperiod ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_accountingperiod FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_auditevent ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_auditevent FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_nominalaccount ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_nominalaccount FORCE ROW LEVEL SECURITY;")

        # Create policies
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_journal
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_journalline
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_accountingperiod
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_auditevent
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_nominalaccount
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)


def drop_postgres_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        # Disable RLS and drop policies
        cursor.execute("ALTER TABLE accounting_journal NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_journal DISABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_journalline NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_journalline DISABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_accountingperiod NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_accountingperiod DISABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_auditevent NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_auditevent DISABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_nominalaccount NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_nominalaccount DISABLE ROW LEVEL SECURITY;")

        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_journal;")
        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_journalline;")
        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_accountingperiod;")
        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_auditevent;")
        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_nominalaccount;")

        # Drop triggers
        cursor.execute("DROP TRIGGER IF EXISTS trigger_check_journal_balance ON accounting_journalline;")
        cursor.execute("DROP TRIGGER IF EXISTS trigger_check_journal_period ON accounting_journal;")
        cursor.execute("DROP TRIGGER IF EXISTS trigger_check_journalline_period ON accounting_journalline;")
        cursor.execute("DROP TRIGGER IF EXISTS trigger_block_audit_log_modification ON accounting_auditevent;")

        # Drop functions
        cursor.execute("DROP FUNCTION IF EXISTS check_journal_balance();")
        cursor.execute("DROP FUNCTION IF EXISTS check_period_not_closed();")
        cursor.execute("DROP FUNCTION IF EXISTS block_audit_log_modification();")

        # Drop role
        cursor.execute("DROP ROLE IF EXISTS ledger_tenant_role;")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NominalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('canonical_taxonomy', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_code', models.CharField(default='OS', max_length=5)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journal')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.nominalaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
        ),
        migrations.RunPython(create_postgres_triggers, drop_postgres_triggers),
    ]
