# Generated by Django 5.2.16 on 2026-07-10 22:00

import django.db.models.deletion
from django.db import migrations, models


def create_vat_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        # Enable & Force RLS
        cursor.execute("ALTER TABLE accounting_vatrate ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_vatrate FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_vatdecisionrule ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_vatdecisionrule FORCE ROW LEVEL SECURITY;")

        # Create policies
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_vatrate
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_vatdecisionrule
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)

        # Grant permissions
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_vatrate TO ledger_tenant_role;")
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_vatdecisionrule TO ledger_tenant_role;")


def drop_vat_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE accounting_vatrate NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_vatrate DISABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_vatdecisionrule NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_vatdecisionrule DISABLE ROW LEVEL SECURITY;")

        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_vatrate;")
        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_vatdecisionrule;")


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatDecisionRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=10)),
                ('supplier_name_pattern', models.CharField(blank=True, default='', max_length=100)),
                ('account_code_pattern', models.CharField(blank=True, default='', max_length=10)),
                ('vat_code', models.CharField(max_length=5)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vat_code', models.CharField(max_length=5)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'vat_code', 'effective_from')},
            },
        ),
        migrations.RunPython(create_vat_policies, drop_vat_policies),
    ]
