# Generated by Django 5.2.16 on 2026-07-10 22:01

import django.db.models.deletion
from django.db import migrations, models


def create_import_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        # Enable & Force RLS
        cursor.execute("ALTER TABLE accounting_importedfile ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_importedfile FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_banktransaction ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_banktransaction FORCE ROW LEVEL SECURITY;")

        # Create policies
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_importedfile
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_banktransaction
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)

        # Grant permissions
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_importedfile TO ledger_tenant_role;")
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_banktransaction TO ledger_tenant_role;")


def drop_import_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE accounting_importedfile NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_importedfile DISABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_banktransaction NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_banktransaction DISABLE ROW LEVEL SECURITY;")

        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_importedfile;")
        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_banktransaction;")


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_vatdecisionrule_vatrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_content', models.TextField()),
                ('file_hash', models.CharField(max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'file_hash')},
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=255)),
                ('fitid', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
                ('imported_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.importedfile')),
            ],
            options={
                'unique_together': {('tenant', 'fitid')},
            },
        ),
        migrations.RunPython(create_import_policies, drop_import_policies),
    ]
