# Generated by Django 5.2.16 on 2026-07-10 22:02

import django.db.models.deletion
from django.db import migrations, models


def create_evidence_policies_and_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        # 1. Enable & Force RLS
        cursor.execute("ALTER TABLE accounting_evidencedocument ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_evidencedocument FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_journalevidencelink ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_journalevidencelink FORCE ROW LEVEL SECURITY;")

        # Create policies
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_evidencedocument
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_journalevidencelink
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)

        # Grant permissions to tenant role
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_evidencedocument TO ledger_tenant_role;")
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_journalevidencelink TO ledger_tenant_role;")

        # 2. Add default review status trigger on Journal inserts
        cursor.execute("""
            CREATE OR REPLACE FUNCTION check_journal_status_default()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.source_type IN ('SalesInvoice', 'SupplierInvoice', 'EmployeeExpense') THEN
                    NEW.status := 'RequiresReview';
                ELSE
                    NEW.status := 'Posted';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        """)
        cursor.execute("""
            CREATE TRIGGER trigger_check_journal_status_default
            BEFORE INSERT ON accounting_journal
            FOR EACH ROW
            EXECUTE FUNCTION check_journal_status_default();
        """)

        # 3. Add status update triggers on link creations/deletions
        cursor.execute("""
            CREATE OR REPLACE FUNCTION update_journal_status_on_link()
            RETURNS TRIGGER AS $$
            BEGIN
                IF TG_OP = 'INSERT' THEN
                    UPDATE accounting_journal
                    SET status = 'Posted'
                    WHERE id = NEW.journal_id AND source_type IN ('SalesInvoice', 'SupplierInvoice', 'EmployeeExpense');
                ELSIF TG_OP = 'DELETE' THEN
                    IF NOT EXISTS (SELECT 1 FROM accounting_journalevidencelink WHERE journal_id = OLD.journal_id) THEN
                        UPDATE accounting_journal
                        SET status = 'RequiresReview'
                        WHERE id = OLD.journal_id AND source_type IN ('SalesInvoice', 'SupplierInvoice', 'EmployeeExpense');
                    END IF;
                END IF;
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;
        """)
        cursor.execute("""
            CREATE TRIGGER trigger_update_journal_status_on_link
            AFTER INSERT OR DELETE ON accounting_journalevidencelink
            FOR EACH ROW
            EXECUTE FUNCTION update_journal_status_on_link();
        """)


def drop_evidence_policies_and_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE accounting_evidencedocument NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_evidencedocument DISABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_journalevidencelink NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_journalevidencelink DISABLE ROW LEVEL SECURITY;")

        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_evidencedocument;")
        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_journalevidencelink;")

        cursor.execute("DROP TRIGGER IF EXISTS trigger_check_journal_status_default ON accounting_journal;")
        cursor.execute("DROP FUNCTION IF EXISTS check_journal_status_default();")

        cursor.execute("DROP TRIGGER IF EXISTS trigger_update_journal_status_on_link ON accounting_journalevidencelink;")
        cursor.execute("DROP FUNCTION IF EXISTS update_journal_status_on_link();")


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_importedfile_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='status',
            field=models.CharField(default='Posted', max_length=20),
        ),
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_content', models.BinaryField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEvidenceLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('linked_by', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.evidencedocument')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='accounting.journal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'journal', 'document')},
            },
        ),
        migrations.RunPython(create_evidence_policies_and_triggers, drop_evidence_policies_and_triggers),
    ]
