# Generated by Django 5.2.16 on 2026-07-10 22:04

import django.db.models.deletion
from django.db import migrations, models


def create_reconciliation_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        # Enable & Force RLS
        cursor.execute("ALTER TABLE accounting_bankreconciliation ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_bankreconciliation FORCE ROW LEVEL SECURITY;")

        # Create policies
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_bankreconciliation
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)

        # Grant permissions
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_bankreconciliation TO ledger_tenant_role;")


def drop_reconciliation_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE accounting_bankreconciliation NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_bankreconciliation DISABLE ROW LEVEL SECURITY;")
        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_bankreconciliation;")


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_journal_status_evidencedocument_journalevidencelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled_by', models.CharField(max_length=100)),
                ('bank_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='accounting.banktransaction')),
                ('matched_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounting.journal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
        ),
        migrations.RunPython(create_reconciliation_policies, drop_reconciliation_policies),
    ]
