# Generated by Django 5.2.16 on 2026-07-10 22:10

import django.db.models.deletion
from django.db import migrations, models


def create_vat_return_policies_and_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        # 1. Enable & Force RLS on VatReturn
        cursor.execute("ALTER TABLE accounting_vatreturn ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_vatreturn FORCE ROW LEVEL SECURITY;")

        # Create policies
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_vatreturn
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)

        # Grant permissions
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_vatreturn TO ledger_tenant_role;")

        # 2. Trigger to block journal edits in locked VAT periods
        cursor.execute("""
            CREATE OR REPLACE FUNCTION check_vat_return_lock()
            RETURNS TRIGGER AS $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM accounting_vatreturn
                    WHERE tenant_id = NEW.tenant_id
                      AND start_date <= NEW.date
                      AND end_date >= NEW.date
                ) THEN
                    RAISE EXCEPTION 'Operation blocked. The date % falls within a locked VAT return period.', NEW.date;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        """)

        cursor.execute("""
            CREATE TRIGGER check_vat_return_lock_trigger
            BEFORE INSERT OR UPDATE ON accounting_journal
            FOR EACH ROW
            EXECUTE FUNCTION check_vat_return_lock();
        """)


def drop_vat_return_policies_and_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TRIGGER IF EXISTS check_vat_return_lock_trigger ON accounting_journal;")
        cursor.execute("DROP FUNCTION IF EXISTS check_vat_return_lock();")
        cursor.execute("ALTER TABLE accounting_vatreturn NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_vatreturn DISABLE ROW LEVEL SECURITY;")
        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_vatreturn;")


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_bankreconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatReturn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.CharField(max_length=100)),
                ('total_output_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_input_vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_vat_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
        ),
        migrations.RunPython(create_vat_return_policies_and_triggers, drop_vat_return_policies_and_triggers),
    ]
