# Generated by Django 5.2.16 on 2026-07-11 08:25

import django.db.models.deletion
from django.db import migrations, models


def create_bank_feed_connection_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE accounting_bankfeedconnection ENABLE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_bankfeedconnection FORCE ROW LEVEL SECURITY;")
        cursor.execute("""
            CREATE POLICY tenant_isolation_policy ON accounting_bankfeedconnection
                FOR ALL
                USING (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''))
                WITH CHECK (tenant_id::text = NULLIF(current_setting('app.current_tenant_id', true), ''));
        """)
        cursor.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON accounting_bankfeedconnection TO ledger_tenant_role;")


def drop_bank_feed_connection_policies(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE accounting_bankfeedconnection NO FORCE ROW LEVEL SECURITY;")
        cursor.execute("ALTER TABLE accounting_bankfeedconnection DISABLE ROW LEVEL SECURITY;")
        cursor.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON accounting_bankfeedconnection;")


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_vatreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatreturn',
            name='hmrc_receipt_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='period_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BankFeedConnection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_identifier', models.CharField(max_length=100)),
                ('status', models.CharField(default='Connected', max_length=20)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('consent_token', models.TextField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenant')),
            ],
        ),
        migrations.RunPython(create_bank_feed_connection_policies, drop_bank_feed_connection_policies),
    ]
