# Generated by Django 5.2.16 on 2026-07-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_harden_vat_lock_and_period_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='HmrcVatConnection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vrn', models.CharField(blank=True, default='', max_length=9)),
                ('status', models.CharField(default='NotConnected', max_length=20)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('scope', models.CharField(blank=True, default='', max_length=120)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_authorised_at', models.DateTimeField(blank=True, null=True)),
                ('last_obligations_sync_at', models.DateTimeField(blank=True, null=True)),
                ('latest_obligations', models.JSONField(blank=True, default=list)),
                ('last_submission_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hmrc_vat_connection', to='accounting.tenant')),
            ],
        ),
    ]
