# Generated by Django 5.2.16 on 2026-07-12 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_hmrcvatconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_key', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('prepared_payload', models.JSONField(blank=True, default=dict)),
                ('evidence_complete', models.BooleanField(default=False)),
                ('bank_reconciled', models.BooleanField(default=False)),
                ('vat_codes_reviewed', models.BooleanField(default=False)),
                ('exceptions_resolved', models.BooleanField(default=False)),
                ('client_approved', models.BooleanField(default=False)),
                ('client_approved_at', models.DateTimeField(blank=True, null=True)),
                ('client_approved_by', models.CharField(blank=True, default='', max_length=100)),
                ('practice_approved_at', models.DateTimeField(blank=True, null=True)),
                ('practice_approved_by', models.CharField(blank=True, default='', max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('hmrc_receipt_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_reviews', to='accounting.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'period_key')},
            },
        ),
    ]
