# Generated by Django 5.2.16 on 2026-07-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_vatreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=160)),
                ('category', models.CharField(default='General', max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(default='Open', max_length=20)),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to='accounting.tenant')),
            ],
        ),
    ]
