# Generated by Django 5.2.16 on 2026-07-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_clientrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='review_status',
            field=models.CharField(default='Unreviewed', max_length=20),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='reviewed_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='review_status',
            field=models.CharField(default='Unreviewed', max_length=20),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='reviewed_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
